spring:
  profiles: generate
  flyway:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    locations: src/main/resources/db/migration
    baselineOnMigrate: true
    validateOnMigrate: true

  jpa:
    database-platform: org.hibernate.dialect.PostgresSQLDialect
    hibernate:
      ddl-auto: none
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  datasource:
     url: ${PROD_DB_URL}
     username: ${PROD_DB_USERNAME}
     password: ${PROD_DB_PASSWORD}
     driver-class-name: org.postgresql.Driver
server:
  port:${PORT:8080}