### Initialize Data
POST http://localhost:8080/admin/data

### Catalog
GET http://localhost:8080/catalog

###
POST http://localhost:8080/orders
Content-Type: application/json

{
    "items": [
      {
        "bookId": 3,
        "quantity": 1
      },
      {
        "bookId": 4,
        "quantity": 2
      }
    ],
    "recipient": {
        "name": "Karolina Rejowska",
        "phone": "123-123-123",
        "street": "Narutowicza 24",
        "city": "Lodz",
        "zipCode": "12-123",
        "email": "rejowskakarolina@gmail.com"
    }
}

###
GET http://localhost:8080/orders

###
DELETE http://localhost:8080/orders/131

###
PUT http://localhost:8080/orders/13/status
Content-Type: application/json

{
  "status": "CANCELED"
}