version: '3'

services:
  db:
    container_name: bookido
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: bookido
        POSTGRES_USER: postgres
        POSTGRES_PASSWOED: qwerty
    ports:
      - 7432:5432