#version: 'v2.13.0'
#
#services:
#  db:
#    container_name: bookido
#    image: postgres:15.1
#    restart: always
#    environment:
#        POSTGRES_DB: bookido
#        POSTGRES_USER: postgres
#        POSTGRES_PASSWORD: qwerty
#    ports:
#      - 7432:5432